### ISSUE TITLE
Introduce categories for the icon list definitions

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-icons#12]
Currently, in jQuery and react articles we have manually creates lists with icons and categories. Thus, the categories might not be ideal and need revision. Our goal is to automatically generate the articles with icons, so we need the categories present in the `icon-list` jsons.

https://github.com/telerik/kendo-icons/blob/develop/src/icons/icons-list.json

**Docs-seed Task** 

https://github.com/telerik/docs-seed/issues/127 

**Existing articles**
- Kendo - https://docs.telerik.com/kendo-ui/styles-and-layout/icons-web#list-of-font-icons
- Blazor - https://docs.telerik.com/blazor-ui/common-features/font-icons#icons-list
- React - https://www.telerik.com/kendo-react-ui/components/styling/icons/#toc-list-of-font-icons
- Angular - https://www.telerik.com/kendo-angular-ui/components/styling/icons/#toc-list-of-font-icons
- Vue - https://www.telerik.com/kendo-vue-ui/components/styling/icons/#toc-list-of-font-icons

**Comment by TeyaVes** [comment]
@Iankodj , the icon's JSON has been added to the icon's package- it is currently shipped and can be used in the docs seed. We've also renamed the groups to categories:

https://github.com/telerik/kendo-icons/blob/develop/src/icons/icons.json
