### ISSUE TITLE
What is the license for these icons?

### ISSUE THREAD

**Issue by fmotion1** [telerik/kendo-icons#149]
I'm interested in using some of the Kendo Icons for personal projects. I noticed there is no `LICENSE` file in the repo. Can someone clarify what license covers these icons?

**Comment by epetrow** [comment]
Hi @fmotion1,

The license files are located  in each of the packages [`font-icons`](https://github.com/telerik/kendo-icons/blob/develop/packages/font-icons/LICENSE.md) and [`svg-icons`](https://github.com/telerik/kendo-icons/blob/develop/packages/svg-icons/LICENSE.md)
