### ISSUE TITLE
New SVG icons seems to be taking the first "empty" (null) slot

### ISSUE THREAD

**Issue by dmanova** [telerik/kendo-icons#30]
It seems that a new SVG icon takes the first "empty" (null) slot in icon-list.json

This way it may not receive the next Unicode number from the proper category. For example the clock-arrow-rotate.svg should be in the "action" category (the same as the clock.svg), but it takes the first empty slot that is in the first category "text" -  hence receives "unicode": "e06f" instead of "unicode": "e15d"

Might be related to this code:
https://github.com/telerik/kendo-icons/blob/1add19d6257d235315f40a86599b516c265be39d/scripts/update-icons.js#L28

**Comment by TeyaVes** [comment]
this is not a bug, but expected behavior, as at the time of populating the icons.json we don't have any information about the category of the icon. Plus, the icon can be part of more than one categories.

**Comment by dmanova** [comment]
Just a note that while keeping both fonts (the one in the kendo-ux repo and the one in the kendo-icons repo) it is good to keep them consistent when it comes to codes and names. And the auto-population violates this, so manual intervention will be needed.
