### ISSUE TITLE
Icons v1.0.0

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-icons#61]
Umbrella for v1 of the icons package.

### Icons Meta

- [x] https://github.com/telerik/kendo-icons/issues/59
- [x] https://github.com/telerik/kendo-icons/issues/37

## Revise Icons options

Currently, the icons support `size` and `flip` options that were implemented a while back. We need to revise those and improve them further to be more flexible and work consistently for both svg and font icons.

- [x] https://github.com/telerik/kendo-icons/issues/58
- [x] https://github.com/telerik/kendo-icons/issues/60

**Comment by zdravkov** [comment]
Adding this one here, too:

- [ ] https://github.com/telerik/kendo-icons/issues/62
