### ISSUE TITLE
Revise Icons Categories

### ISSUE THREAD

**Issue by TeyaVes** [telerik/kendo-icons#94]
While working on the design docs, we've noticed that there are icon categories that contain only one icon which seem to be mistaken, e.g:

- file
- image
- color

In addition, we've agreed with Design Team to revise these icon categories and make them intuitive so that the icon search is easier.

**Comment by imasyuko** [comment]
Previously, there were 10 groups of icons:
- Actions
- Alerts and Notifications
- Editing
- Files and Folders
- Images
- Layout and Navigation
- Mapping
- Media
- Social Sharing
- Toggle

Now there are 28 groups:
- Actions
- Arrows
- Border
- Charts
- Color
- CSS
- Data
- Display
- Editing 
- File 
- Files
- Image
- Images
- Layout
- List
- Maps
- Media
- Navigation
- Notifications
- Outline
- Padding
- Position
- Resize
- Social
- Text
- Text-Formatting
- Toggle
- Typography

Ideas for alternative grouping:
- Arrows - there are missing icons that could be added to this group - arrow-45-down-left; arrow-45-down-right; arrow-45-down-left; arrow-45-down-right, etc.;
- Border - better be plural, just like Actions, Arrows, Images;
- Color - there is only 1 icon that could go into the Images and Editing groups
- Data - there are missing icons that could be added to this group - data; data-web; data-json; data-rest; data-sql; data-csv; validation-data; file-data; 
- Display - not sure why we need that group; 4 icons that are also part of the CSS group;
- File - there is only 1 icon that could go into the Files and Folders group;
- Image - there is only 1 icon that could go into the Images group
- Outline - not sure why we need that group; these 2 icons are part of the CSS group
- Resize - 2 icons that could be added to the Editing group
- Position - not sure why we need that group; 4 icons that are also part of the CSS group
- Text and Typography are similar to the Text-Formatting group and could be merged
